export const REGIONES_CHILE = {
  "Arica y Parinacota": [
    "Arica",
    "Camarones",
    "Putre",
    "General Lagos",
  ],
  "Tarapacá": [
    "Iquique",
    "Alto Hospicio",
    "Pozo Almonte",
    "Camiña",
    "Colchane",
    "Huara",
    "Pica",
  ],
  "Antofagasta": [
    "Antofagasta",
    "Mejillones",
    "Sierra Gorda",
    "Taltal",
    "Calama",
    "Ollagüe",
    "San Pedro de Atacama",
    "Tocopilla",
    "María Elena",
  ],
  "Atacama": [
    "Copiapó",
    "Caldera",
    "Tierra Amarilla",
    "Chañaral",
    "Diego de Almagro",
    "Vallenar",
    "Alto del Carmen",
    "Freirina",
    "Huasco",
  ],
  "Coquimbo": [
    "La Serena",
    "Coquimbo",
    "Andacollo",
    "La Higuera",
    "Paihuano",
    "Vicuña",
    "Illapel",
    "Canela",
    "Los Vilos",
    "Salamanca",
    "Ovalle",
    "Combarbalá",
    "Monte Patria",
    "Punitaqui",
    "Río Hurtado",
  ],
  "Valparaíso": [
    "Valparaíso",
    "Viña del Mar",
    "Concón",
    "Quilpué",
    "Villa Alemana",
    "San Antonio",
    "Quillota",
    "Los Andes",
    "San Felipe",
  ],
  "Metropolitana de Santiago": [
    "Santiago",
    "Providencia",
    "Las Condes",
    "Ñuñoa",
    "La Florida",
    "Maipú",
    "Puente Alto",
    "San Bernardo",
    "Colina",
    "Melipilla",
    "Talagante",
  ],
  "O'Higgins": [
    "Rancagua",
    "Machalí",
    "San Fernando",
    "Santa Cruz",
    "Pichilemu",
  ],
  "Maule": [
    "Talca",
    "Curicó",
    "Linares",
    "Cauquenes",
  ],
  "Ñuble": [
    "Chillán",
    "San Carlos",
    "Bulnes",
  ],
  "Biobío": [
    "Concepción",
    "Talcahuano",
    "Los Ángeles",
    "Coronel",
  ],
  "La Araucanía": [
    "Temuco",
    "Angol",
    "Villarrica",
    "Pucón",
  ],
  "Los Ríos": [
    "Valdivia",
    "La Unión",
    "Río Bueno",
  ],
  "Los Lagos": [
    "Puerto Montt",
    "Osorno",
    "Castro",
    "Ancud",
  ],
  "Aysén": [
    "Coyhaique",
    "Aysén",
    "Cochrane",
  ],
  "Magallanes y de la Antártica Chilena": [
    "Punta Arenas",
    "Puerto Natales",
    "Porvenir",
  ],
};
